# Generated by Django 3.2.7 on 2021-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default=None, max_length=100)),
                ('state', models.CharField(default='/', max_length=200)),
            ],
        ),
    ]
