# Generated by Django 3.2.7 on 2021-09-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigremont_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemontObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
