# Generated by Django 3.2.7 on 2021-09-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigremont_app', '0005_auto_20210919_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заявки')),
                ('date_of_delivery', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterField(
            model_name='worktype',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='bigremont_app.Material', verbose_name='Материалы'),
        ),
        migrations.CreateModel(
            name='ApplicationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigremont_app.application')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigremont_app.material')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, through='bigremont_app.ApplicationMaterial', to='bigremont_app.Material', verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='application',
            name='remont_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigremont_app.remontobject', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='application',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigremont_app.worktype', verbose_name='Вид работ'),
        ),
    ]
