# Generated by Django 3.2.7 on 2021-09-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigremont_app', '0006_auto_20210920_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.AlterField(
            model_name='application',
            name='materials',
            field=models.ManyToManyField(blank=True, through='bigremont_app.ApplicationMaterial', to='bigremont_app.Material', verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='materials',
            field=models.ManyToManyField(blank=True, to='bigremont_app.Material', verbose_name='Материалы'),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigremont_app.telegramuser', verbose_name='пользователь бота')),
            ],
            options={
                'verbose_name': 'Получатель заявок',
                'verbose_name_plural': 'Получатели заявок',
            },
        ),
    ]
