# Generated by Django 3.2.7 on 2021-09-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigremont_app', '0007_auto_20210921_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True),
        ),
    ]
