# Generated by Django 3.2.7 on 2021-09-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigremont_app', '0008_alter_telegramuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='RecipientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigremont_app.telegramgroup', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'Получатель заявок(Группа)',
                'verbose_name_plural': 'Получатели заявок(Группа)',
            },
        ),
    ]
